FROM node:22-alpine AS builder
WORKDIR /app

ENV INTERNAL_BACKEND_URL="https://alamega-api.onrender.com"
ENV NEXT_PUBLIC_BACKEND_URL="https://alamega-api.onrender.com"

COPY . .
RUN npm install
RUN npm run build

FROM node:22-alpine AS runner

ENV INTERNAL_BACKEND_URL="https://alamega-api.onrender.com"

ENV NEXT_TELEMETRY_DISABLED=1
ENV NODE_ENV=production
WORKDIR /app
COPY --from=builder /app .

CMD ["npm", "start"]