services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres_password}
      POSTGRES_DB: ${POSTGRES_DB:-postgres_db}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres_user} -d ${POSTGRES_DB:-postgres_db}" ]
      interval: 3s
      timeout: 3s
      retries: 10
      start_period: 5s
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  backend:
    build: ./backend
    environment:
      JDBC_URL: jdbc:postgresql://db:5432/${POSTGRES_DB:-postgres_db}?user=${POSTGRES_USER:-postgres_user}&password=${POSTGRES_PASSWORD:-postgres_password}
      JWT_SECRET: ${JWT_SECRET:-SECRET}
      ADMIN_USERNAME: ${ADMIN_USERNAME:-ALAMEGA}
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: [ "CMD-SHELL", "bash -c '</dev/tcp/localhost/8080'" ]
      interval: 3s
      timeout: 3s
      retries: 10
      start_period: 5s
    volumes:
      - maven_cache:/root/.m2
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      args:
        INTERNAL_BACKEND_URL: http://backend:8080
        NEXT_PUBLIC_BACKEND_URL: /api
    environment:
      NEXT_SERVER_ACTIONS_ENCRYPTION_KEY: ${NEXT_SERVER_ACTIONS_ENCRYPTION_KEY:-YLj1hAUGheMPZNo3ixrmSAdl+uQJVWgeCv8ilKydQxY=}
    depends_on:
      backend:
        condition: service_healthy
    healthcheck:
      test: [ "CMD-SHELL", "wget -qO- http://localhost:3000 || exit 1" ]
      interval: 3s
      timeout: 3s
      retries: 10
      start_period: 5s
    volumes:
      - npm_cache:/app/node_modules
    networks:
      - app-network

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost" ]
      interval: 3s
      timeout: 3s
      retries: 10
      start_period: 5s
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
  maven_cache:
  npm_cache: